name: 'Create Pull Request'
description: 'This action creates and attemps to automatically merge pull requests'
inputs:
  title:
    description: Title of the pull request
    required: true
  repo:
    description: Repository name with owner. (owner/repo)
    default: ${{ github.repository }}
  head:
    description: Head branch to merge.
    default: ${{ github.ref_name }}
  base:
    description: Base branch to merge into.
    default: ${{ github.event.repository.default_branch }}
  labels:
    description: A comma seperated list of labels to add to the pull request.
  automerge:
    description: True if the pull request should be merged automatically.
    default: true
  token:
    description: GitHub access token.
    required: true
outputs:
  number:
    description: Number of the pull request.
  url:
    description: Url of the pull  request.
runs:
  using: 'node20'
  main: 'dist/index.js'
